baseURL = "http://nvkp.github.io/sparql-cheatsheet/"
languageCode = "en-GB"
title = "SPARQL 1.1 Cheat Sheet"
enableGitInfo = true

[params]
    BookTheme = 'auto'
    BookSearch = true
    BookRepo = 'https://github.com/nvkp/sparql-cheatsheet'